"""empty message

Revision ID: 86288cc57efe
Revises: 
Create Date: 2018-06-29 19:36:46.998661

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '86288cc57efe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthill_session',
                    sa.Column('session_key', sa.String(length=40), nullable=False),
                    sa.Column('session_data', sa.Text(), nullable=False),
                    sa.Column('expire_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('session_key'),
                    sa.UniqueConstraint('session_key')
                    )
    op.create_index(op.f('ix_anthill_session_expire_date'), 'anthill_session', ['expire_date'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('last_login', sa.DateTime(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('username', sa.String(length=128), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_anthill_session_expire_date'), table_name='anthill_session')
    op.drop_table('anthill_session')
    # ### end Alembic commands ###
